HDest-Community/Ugly-as-Sin

modules/ai/tracker.zsc
Monsters now search the last point they saw the player, the point where they saw the player was headed, and six points in a radial search around that second point.
UaS_LastKnownMarker is now descended from Actor and will be visible in-game if UaS_Debug is set to 1. In addition, there is a debug message that informs you when a monster has reached a node in its search path and is moving on to the next.
=> Added more complex investigative pathing.

modules/looting/loottables.zsc
Spawning armour that way crashes the game
=> Remove armour from ZM66 marine loot table

modules/items/traumakit/traumakit_biofoam.zsc
* Changes 'antispetic' to 'antiseptic'.
* Changes 'absorbant' to 'absorbent'; technically both are correct but absorbent is the more commonly-used term, from my research.
=> Fixes biofoam typo.

modules/items/traumakit/traumakit.zsc
An alternate approach to fixing #133; #134 was way too complicated.
This means we no longer keep track of the current wound in two separate ways; this allowed for desyncs between them like what caused #133. Now, we only keep track of the current wound, and find the index based on its position in the list. This means that when something is removed from `wh.critwounds`, the index of the current wound is automatically updated.
=> Trauma Kit: Removes TK_WOUNDINDEX, fixes #133

deathfade/module/deathfade.zsc
Fixes deathfade being applied to all players when the first player to die has it enabled.
=> Deathfade: Fix wrong user's cvar being checked.

scarcity/module/scarcity_remover.zsc
Prevents soft-locks caused by actors essential to progression being removed or being replaced without the special being copied over.
=> Scarcity: Don't remove/replace special things

buildscripts/makefile, textures.txt
Fixes LZDoom failing to load composite textures.
=> Strip leading forward slash from TEXTUREs patches

core/module/core.zsc, gldefs.txt
Removes all remaining references to the vignette shader (they were causing LZDoom to abort on level load).
=> Remove unused vignette shader

ammopouch/module/ammopouch.zsc
Fixes not being able to take off armor with an ammo pouch in your inventory.
=> Ammopouch: Don't block hd_strip

2fcartridges/module/2f_bootstrap.zsc
Fixes the suture module handler being removed on maps with the ResetInventory mapinfo property set.
=> Do suture module bootstrap on tick

medical/module/traumakit/traumakit.zsc
Generalizes the trauma kit strip check a little. Custom worn items will block wound access with a general "remove worn layers" message.
=> Traumakit: Generalize strip check

medical/module/traumakit/traumakit_hud.zsc
In #175, I forgot to add a check to prevent `-No wounds selected-` from appearing when you have no treatable wounds.
This should fix that.
=> Medical: Fix minor oversight with trauma kit UI

medical/module/traumakit/traumakit_painkiller.zsc
Each use of anaesthetic counts as ¹/₂₀ᵗʰ of a stim use, as outlined in #117.
HOWEVER: This means that using one stim and 4 anaesthetics will put you at the OD threshold, because a stim is 400 stimcount and the overdose is at 480 stimcount. I think this should probably be tweaked somewhat, or there should be a way to tell if you're too close to the OD limit to safely use anaesthetics. When I play, I try to ration my painkillers and only use them on things that need a lot of biofoam or obstructions (and only use two full doses for something with both), but I think this might become a noob trap.
One potential idea is to make stims themselves act as a low-level anaesthetic for all wounds, so that anaesthetic is less necessary if you've already used one, but that might just make it so that the …
=> [NEEDS BALANCING] Make traumakit painkillers contribute to stim OD

medical/module/medical_handler.zsc
Had to use countinv instead of the actual stimcount variable. Also, it was rounding down to zero because integer division.
=> Fix stimcount painkiller factor rounding to zero

ai/cvarinfo.txt, ai/menudef.txt, ai/module/ai_flashlight.zsc, ai/module/ai_wounded.zsc, cvarinfo.txt, laserlight/module/laser.zsc, menudef.txt
- Incapacitated enemies can now 'play dead,' which means they will turn their flashlight or laser off.
- This was actually surprisingly effective in playtesting, since I got really used to checking for lights instead of actually checking to see if monsters were really dead or not.
- The chance for an enemy to play dead every light recheck is configurable.
- Incapacitated enemies will no longer have aim jitter.
- Incapacitated enemies will no longer jitter their flashlight/laser module around. (Formerly, this would stack with the normal damage jitter from wounding, causing it to aim all over the place.)
- An enemy being incapacitated has a HealthFactor of 0.1 for the duration of the incapacitation.
=> Tweak incapacitated enemy AI

2fcartridges/module/2f.zsc
Just changes the help text to be displayed with `A_Log()` instead.
Credits to Undead_Zeratul for finding this.
=> 2fcartridges: Only show help message to user

core/menudef.txt, menudef.txt
Moves the settings option from `HDOptionsMenu` to `HDAddonMenu`, which was introduced recently.
=> menudef: Move settings to HDAddonMenu

scarcity/module/scarcity.zsc
This is mostly for the modified NewRange, but also so the vanilla Range stays clean.
=> Prevent Scarcity from running on The Range

deathfade/module/deathfade.zsc
Very handy when someone accidentally left this option on while playing coop (they can't see anything)
=> deathfade: Allow players to enable/disable when already dead

deathfade/module/deathfade.zsc
In multiplayer, if a player dies with deathfade enabled, and leaves the game, everyone else will suffer a VM abort.
This just adds a simple check to see if the player still exists.
=> deathfade: Fix VM aborts caused by a dead player leaving with deathfade on

LANGUAGE, looting/LANGUAGE, looting/module/looting.zsc
Was hoping to use the `LWPHELP_USE` constant, but that's defined in `HDWeapon`, not `Inventory`, so instead the value that the constant uses was copied.
=> Localize Looting Help Text

LANGUAGE, medical/language, medical/module/medical_tool.zsc, medical/module/medical_wound.zsc, medical/module/selfbandage/selfbandage.zsc, medical/module/selfbandage/selfbandage_bandage.zsc, medical/module/selfbandage/selfbandage_hud.zsc, medical/module/traumakit/traumakit.zsc, medical/module/traumakit/traumakit_biofoam.zsc, medical/module/traumakit/traumakit_forceps.zsc, medical/module/traumakit/traumakit_helptext.zsc, medical/module/traumakit/traumakit_hud.zsc, medical/module/traumakit/traumakit_painkiller.zsc, medical/module/traumakit/traumakit_saline.zsc, medical/module/traumakit/traumakit_scalpel.zsc, medical/module/traumakit/traumakit_stapler.zsc, medical/module/traumakit/traumakit_supplies.zsc, medical/module/traumakit/traumakit_sutures.zsc
Not sure if this is best way to handle the new LANGUAGE changes, but it should at least remove some redundant parts and tidy up some of the code.
note: still questioning on how to handle wound descriptions, and let me know if there's a cleaner way to implement the language stuff
=> Medical: language refactor

medical/module/medical_wound.zsc
Prevents some funky visual effects from happening (not the good kind)
Also this is done with the assumption that the minimum alpha value is `0.3` since the calculation is `max((depth/width), 0.3)`
=> medical: Clamp visual wound alpha

LANGUAGE, medical/language, medical/module/selfbandage/selfbandage.zsc, medical/module/traumakit/traumakit.zsc, medical/readme.md
(suggested by Sledge)
Allows the Trauma Kit to rip bandages by holding down Fire.
Should hopefully make the Trauma Kit less clunky (i.e: no more switching back and forth just to rip bandages)
Note: I also simplified the checks in `HandleStrip()` a bit. If you prefer how it was before, let me know and I'll revert it back.
=> medical: Allow the Trauma Kit to rip bandages

stabilizer/module/stabilizer.zsc
fixes an error in pickupmessage. referred to $PICKUP_STABILIZER but now refers to proper tag, $PICKUP_GYROSTABILIZER
=> Fix gyro stabilizer's pickup message

medical/module/medical_wound.zsc, medical/module/selfbandage/selfbandage_hud.zsc, medical/textures.txt, textures.txt
Makes wounds and blood droplets use the player's blood colour for its coloring.
Additionally, I updated the bandage's wound icons to be the same as the visual wounds. (they also use the player's blood colour)
In order to get the visual wound particles to properly tint to the player's blood colour, I had to create the following textures `UASBLUDA0`, `UASBLUDB0`, `UASBLUDC0`.
They are basically the same as the normal BLUD textures, just desaturated to be greyscale for the tinting to work properly.
The wound rendering also now uses `STYLE_Shaded` instead of `STYLE_Normal`, as the latter rendering style doesn't seem to tint that well.
Unfortunately, `STYLE_Shaded` seems to apply a lot of transparency to the texture, so the alpha is multiplied by 2 to make it more visible. (unless there's no …
=> Medical: Use player blood colour for wounds/blood droplets

laserlight/module/laser.zsc
For some reason, the HERP's laser freaks out when trying to pitch to a `target`
This PR just adds a check to exclude HERPs from the target pitch check, as it seems to work fine without it.
Should hopefully fix #225
=> laserlight: fix herp laser jittering due to it trying to target enemies
